[[inputs.elasticsearch]]
  servers = ["http://$AGENT_IP:9200"]
  http_timeout = "5s"
  local = false
  cluster_health = true
  cluster_stats = true
  indices_include = ["_all"]
  indices_level = "shards"
  node_stats = ["jvm", "http", "breaker"]