services:
  agent-api:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: agent_api
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/agent:/opt/agent