status = error

# Console Appender
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

# Root Logger
rootLogger.level = info
rootLogger.appenderRef.console.ref = console

# Deprecation Logger (to stdout)
logger.deprecation.name = org.opensearch.deprecation
logger.deprecation.level = deprecation
logger.deprecation.additivity = false
logger.deprecation.appenderRef.console.ref = console

# Search Slowlog (to stdout)
logger.index_search_slowlog_rolling.name = index.search.slowlog
logger.index_search_slowlog_rolling.level = info
logger.index_search_slowlog_rolling.additivity = false
logger.index_search_slowlog_rolling.appenderRef.console.ref = console

# Indexing Slowlog (to stdout)
logger.index_indexing_slowlog.name = index.indexing.slowlog.index
logger.index_indexing_slowlog.level = info
logger.index_indexing_slowlog.additivity = false
logger.index_indexing_slowlog.appenderRef.console.ref = console

# Task Details Log (to stdout)
logger.task_detailslog_rolling.name = task.detailslog
logger.task_detailslog_rolling.level = info
logger.task_detailslog_rolling.additivity = false
logger.task_detailslog_rolling.appenderRef.console.ref = console
