transport.port: 9300
http.port: 9200

action.auto_create_index: true

node.name: $AGENT_ID
network.host: 0.0.0.0
cluster.name: $CLUSTER_ID
network.publish_host: $AGENT_IP
node.roles: [cluster_manager,data]

bootstrap.memory_lock: true

plugins.security.ssl.transport.enabled: true
plugins.security.ssl.transport.pemcert_filepath: node.pem
plugins.security.ssl.transport.pemkey_filepath: node-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.ssl.http.enabled: false
plugins.security.ssl.http.pemcert_filepath: api.pem
plugins.security.ssl.http.pemkey_filepath: api-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem

plugins.security.allow_unsafe_democertificates: false
plugins.security.allow_default_init_securityindex: false

plugins.security.disabled: true
plugins.security.audit.type: log4j
plugins.security.audit.config.enable_rest: false
plugins.security.audit.config.enable_transport: false
plugins.security.audit.config.log_request_body: false
plugins.security.enable_snapshot_restore_privilege: false
plugins.security.check_snapshot_restore_write_privileges: false
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: false
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

plugins.security.authcz.admin_dn:
  - 'CN=opensearch-node.service.consul'
plugins.security.nodes_dn:
  - 'CN=opensearch-node.service.consul'

discovery.seed_hosts: [ $OPENSEARCH_NODES ]
cluster.initial_cluster_manager_nodes: $OPENSEARCH_0

